fint:
  kafka:
    topic:
      org-id: 'fintlabs-no'
      domain-context: kontroll
    application-id: ${fint.application-id}
    default-replicas: 1
spring:
  kafka:
    consumer:
      group-id: 'fint-kontroll-messenger'

