fint:
  kafka:
    topic:
      org-id: ${fint.org-id-kafka}
      domain-context: kontroll
    application-id: ${fint.application-id}
spring:
  kafka:
    consumer:
      group-id: ${fint.application-id}
#      group-id: test-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
    properties:
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.trusted.packages: 'no.fintlabs.message'
      spring.json.value.default.type: 'no.fintlabs.message.Message'
    bootstrap-servers: localhost:9092

