fint:
  org-id: fintlabs.no
  application-id: fint-kontroll-messenger
  kontroll:
    authorization:
      authorized-role: 'https://role-catalog.vigoiks.no/vigo/kontroll/user'
      authorized-admin-role: 'https://role-catalog.vigoiks.no/vigo/kontroll/admin'
      authorized-org-id: 'vigo.no'
    slack:
      url: http://localhost/
      enabled: false

spring:
  threads:
    virtual:
      enabled: true

  main:
    lazy-initialization: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam

  profiles:
    include:
      - kafka

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    no.fintlabs.assignment: INFO
    #    org.hibernate.SQL: INFO
    #    org.hibernate.orm.jdbc.bind: INFO
    no.fintlabs.cache.ehcache: WARN
    org.springframework.security: INFO
    org.springframework.security.web.access.ExceptionTranslationFilter: INFO

server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
