fint:
  org-id: fintlabs.no
  application-id: fint-kontroll-messenger
  kontroll:
    authorization:
      authorized-org-id: 'vigo.no'
    slack:
      url: http://localhost/
      enabled: false

spring:
  threads:
    virtual:
      enabled: true

  main:
    lazy-initialization: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    no.fintlabs.assignment: INFO
    #    org.hibernate.SQL: INFO
    #    org.hibernate.orm.jdbc.bind: INFO
    no.fintlabs.cache.ehcache: WARN

server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
