apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-messenger
  app.kubernetes.io/instance: fint-kontroll-messenger_fintlabs_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no
patches:
  - patch: |-
      - op: add
        path: "/spec/resources"
        value:
          limits:
            cpu: "2000m"
            memory: "2000Mi"
          requests:
            cpu: "1000m"
            memory: "1024Mi"

      - op: replace
        path: "/spec/env/1/value"
        value: "fintlabs-no"
        
      - op: replace
        path: "/spec/env/2/value"
        value: "-XX:+ExitOnOutOfMemoryError -Xmx1950m"
    target:
      kind: Application
      name: fint-kontroll-messenger

  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-beta-vault/items/kontroll-slack-beta-fintlabs-no"

    target:
      kind: OnePasswordItem
      name: fint-kontroll-slack-secrets
